/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia.pkg5;

import javax.swing.JOptionPane;

/**
 *
 * @author samuel y natalia
public class APP2 extends javax.swing.JFrame {

    /**
     * Creates new form APP2
     */
    public APP2() {
        initComponents();
       
        
        btnInsertar.setEnabled(false);
        panelito1.setVisible(false);
        
    }
     String[] letras = new String[10];

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnProcesarMenu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        panelito1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtArray = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelito2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtPegar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtOpcion = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Ingrese la opción que Desea:");

        btnProcesarMenu.setText("Procesar");
        btnProcesarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarMenuActionPerformed(evt);
            }
        });

        jLabel5.setText("0. Salir");

        jLabel6.setText("ingrese las letras (10 en total)");

        txtArray.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtArrayKeyTyped(evt);
            }
        });

        btnInsertar.setText("insertar+");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelito1Layout = new javax.swing.GroupLayout(panelito1);
        panelito1.setLayout(panelito1Layout);
        panelito1Layout.setHorizontalGroup(
            panelito1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelito1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelito1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(panelito1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(txtArray, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnInsertar)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        panelito1Layout.setVerticalGroup(
            panelito1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelito1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelito1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtArray, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertar))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jLabel1.setText("1.Para ingresar las letras");

        jLabel7.setText("las letras ingresadas son:");

        txtPegar.setText("                        ");

        javax.swing.GroupLayout panelito2Layout = new javax.swing.GroupLayout(panelito2);
        panelito2.setLayout(panelito2Layout);
        panelito2Layout.setHorizontalGroup(
            panelito2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelito2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelito2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtPegar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelito2Layout.setVerticalGroup(
            panelito2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelito2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txtPegar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jLabel2.setText("2. Ordenar de manera Ascendente ");

        jLabel3.setText("3. Mostrar letras Ingresadas");

        txtOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOpcionActionPerformed(evt);
            }
        });
        txtOpcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOpcionKeyTyped(evt);
            }
        });

        jButton1.setText("Regresar para ver las demas Aplicaciones");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnProcesarMenu))
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelito2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(panelito1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProcesarMenu)))
                    .addComponent(panelito2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(panelito1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void limpiar() {

    }

    public void burbuja() {
        //metodo de la burbuja para ordenar el array
        for (int j = 0; j < 4; j++) {
            for (int i = 0; i < 4 - j; i++) {
                if (letras[i].compareTo(letras[i + 1]) > 0) {
                    String aux;
                    aux = letras[i];
                    letras[i] = letras[i + 1];
                    letras[i + 1] = aux;
                }
            }
        }

    }

    public void impresion() {
        String cadena="";
        for (int i = 0; i < letras.length; i++) {
            cadena=cadena+letras[i];
         
          
         //   System.out.println(letras[i]);
        }
           txtPegar.setText(cadena);
    }
    private void btnProcesarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarMenuActionPerformed

        String eleccion;
        int num;

        eleccion = txtOpcion.getText();
        num = Integer.parseInt(eleccion);
        txtOpcion.setText("");

        if (num < 0 || num > 3) {
            JOptionPane.showMessageDialog(null, "ingrese una opcion valida");

        } else {

            switch (num) {
                case 1:
                txtArray.setText("");
                txtArray.setEnabled(true);
                btnInsertar.setEnabled(false);
                panelito1.setVisible(true);
                btnProcesarMenu.setEnabled(false);
                txtOpcion.setEnabled(false);
                txtPegar.setText("");
                break;
                case 2:

                if(txtArray.getText().equals("")){
                    JOptionPane.showMessageDialog(null,"aun no se ingresa una cadena de texto para ordenar!");
                }else{
                    burbuja();
                    JOptionPane.showMessageDialog(null, "serie de letras ordenadas !");
                    btnProcesarMenu.setEnabled(true);
                    txtOpcion.setEnabled(true);
                    txtPegar.setText("");

                }
                break;
                case 3:
                impresion();

                break;
                case 0:
                System.exit(0);
                break;
            }
        }
    }//GEN-LAST:event_btnProcesarMenuActionPerformed

    private void txtArrayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtArrayKeyTyped
        // TODO add your handling code here:

        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
        } else {
            evt.consume();
        }
        if (txtArray.getText().length() >= 10) {
            evt.consume();//validacion de maximo de letras

        }
        if (txtArray.getText().length() > 9) {
            btnInsertar.setEnabled(true);
            txtArray.setEnabled(false);
        }
    }//GEN-LAST:event_txtArrayKeyTyped

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        for (int i = 0; i < 10; i++) {
            letras[i] = "";
        }

        int i;
        String letritas = txtArray.getText(); //para recorrer la cadena de texto y despues leerla caracter --
        for (i = 0; i < 10; i++) {                   //por caracter y ingresarlo en un array string
            letras[i] = Character.toString(letritas.charAt(i));
        }

        panelito1.setVisible(false);//ocultar el panel al presionar el boton
        btnProcesarMenu.setEnabled(true);
        txtOpcion.setEnabled(true);
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void txtOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOpcionActionPerformed

    }//GEN-LAST:event_txtOpcionActionPerformed

    private void txtOpcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOpcionKeyTyped
        //validacion para que ingrese letras
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtOpcionKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
                dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(APP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(APP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(APP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(APP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new APP2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnProcesarMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel panelito1;
    private javax.swing.JPanel panelito2;
    private javax.swing.JTextField txtArray;
    private javax.swing.JTextField txtOpcion;
    private javax.swing.JLabel txtPegar;
    // End of variables declaration//GEN-END:variables
}
